project_name: hduhelp-interview
env:
  - GO111MODULE=on
builds:
  - env:
      - CGO_ENABLED=0
    ldflags: -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: 32bit
      amd64: 64bit
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - config.yml.example
      - LICENSE
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'